### ISSUE TITLE
Have trouble installing to nanopi T4 running armbian

### ISSUE THREAD

**Issue by cdplayer** [futurejones/swift-arm64#3]
Seems to successfully run script. 
**curl -s https://packagecloud.io/install/repositories/swift-arm/debian/script.deb.sh | sudo bash**
but when using apt to install it can't find swift4.

$ **sudo apt install swift4**
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package swift4
```

doing **sudo apt search swift** shows nothing that appears to be swift on arm...
$ **uname -a**

`Linux nanopct4 4.4.156-rk3399 #23 SMP Wed Sep 19 11:56:15 CEST 2018 aarch64 aarch64 aarch64 GNU/Linux`

$ **cat /etc/lsb-release** 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
```

$ **cat /etc/apt/sources.list.d/swift-arm_debian.list**
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/swift-arm/debian

deb https://packagecloud.io/swift-arm/debian/ubuntu/ bionic main
deb-src https://packagecloud.io/swift-arm/debian/ubuntu/ bionic main
```

_incidentally it would be really nice to have swift included as an installable from the armbian-config menu._

**Comment by futurejones** [comment]
@cdplayer The reason it cant find "swift4" is because there isn't an install package for Ubuntu 18.04 yet.
I will upload one later today.

**Comment by cdplayer** [comment]
Thanks, Installs now, but will not build Kitura sample. 

$ sudo apt install swift4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libcurl4 libcurl4-openssl-dev
Suggested packages:
  libcurl4-doc libidn11-dev libkrb5-dev libldap2-dev librtmp-dev libssh2-1-dev
Recommended packages:
  swift-lite-build
The following packages will be REMOVED:
  libcurl3
The following NEW packages will be installed:
  libcurl4 libcurl4-openssl-dev swift4
0 upgraded, 3 newly installed, 1 to remove and 0 not upgraded.
Need to get 97.5 MB/97.7 MB of archives.
After this operation, 1,302 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ports.ubuntu.com bionic-security/main arm64 libcurl4 arm64 7.58.0-2ubuntu3.3 [180 kB]
Get:2 https://packagecloud.io/swift-arm/debian/ubuntu bionic/main arm64 swift4 arm64 4.1 [97.3 MB]
Fetched 97.5 MB in 20s (4,830 kB/s)                                                                                                     
(Reading database ... 77372 files and directories currently installed.)
Removing libcurl3:arm64 (7.58.0-2ubuntu2) ...
Selecting previously unselected package libcurl4:arm64.
(Reading database ... 77365 files and directories currently installed.)
Preparing to unpack .../libcurl4_7.58.0-2ubuntu3.3_arm64.deb ...
Unpacking libcurl4:arm64 (7.58.0-2ubuntu3.3) ...
Selecting previously unselected package libcurl4-openssl-dev:arm64.
Preparing to unpack .../libcurl4-openssl-dev_7.58.0-2ubuntu3.3_arm64.deb ...
Unpacking libcurl4-openssl-dev:arm64 (7.58.0-2ubuntu3.3) ...
Selecting previously unselected package swift4.
Preparing to unpack .../archives/swift4_4.1_arm64.deb ...
Unpacking swift4 (4.1) ...
Setting up libcurl4:arm64 (7.58.0-2ubuntu3.3) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2) ...
Setting up libcurl4-openssl-dev:arm64 (7.58.0-2ubuntu3.3) ...
Setting up swift4 (4.1) ...
$ swift build
/usr/bin/swift-build: /usr/lib/aarch64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/bin/../lib/swift/linux/libFoundation.so)
$ swift --version
Swift version 4.1 (swift-4.1-RELEASE)
Target: aarch64-unknown-linux-gnu
$ echo 'print("Hello, world!")' > hello.swift
$ cat hello.swift 
print("Hello, world!")
$ swiftc hello.swift 
$ ./hello 
Hello, world!

$ swift 
```
Welcome to Swift version 4.1 (swift-4.1-RELEASE). Type :help for assistance.
  1> import Foundation
/usr/lib/swift/CoreFoundation/CoreFoundation.h:25:10: note: while building module 'SwiftGlibc' imported from /usr/lib/swift/CoreFoundation/CoreFoundation.h:25:
#include <sys/types.h>
         ^

<module-includes>:3:10: note: in file included from <module-includes>:3:
#include "///usr/include/utmp.h"

```

**Will not include Foundation. Seems to be related to this reference. https://bugs.swift.org/browse/SR-3648**

$ export C_INCLUDE_PATH=/usr/lib/swift/clang/include
$ export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
$ swift
```
Welcome to Swift version 4.1 (swift-4.1-RELEASE). Type :help for assistance.
  1> import Foundation
Relocation type not implemented yet!
UNREACHABLE executed at /home/rock64/swift-source/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp:356!
Aborted
```
$ cd /home/rock64
`bash: cd: /home/rock64: No such file or directory`

**Is this a thing to report to Armbian or FriendlyArm?**

**Another attempt inserting import to hello.swift**
$ cat hello.swift
```
import Foundation
print("Hello, world!")
```
$ swiftc hello.swift
```
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_version@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_slist_append@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_strerror@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_init@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_setopt@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_assign@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_socket_action@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_global_init@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_3'
/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_version_info@CURL_OPENSSL_3'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by futurejones** [comment]
Working on a 4.2 Release that should fix these issues.
